# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

!pip -q install cartopy scipy xarray dask netCDF4 h5netcdf
!pip -q install xarray dask scipy scikit-learn statsmodels h5netcdf netCDF4

"""
Figure 10 — Corrected sector-wise lag correlations, 2008–2025.

Panels
------
(a) SIC vs SST
(b) SIC vs wind speed
(c) SIC vs MLD
(d) SIC vs 2 m air temperature
(e) SIC vs Argo OHC (0–100 m), third-row left
(f) SIC vs surface ocean-current speed, third-row right

Corrections implemented
-----------------------
1. Uses the same 13 Antarctic marginal-sea sectors used elsewhere in the study.
2. Applies one SST-derived static ocean mask to SIC, SST, MLD, ERA5 wind,
   ERA5 T2m, ocean-current speed, and gridded OHC (when that OHC source is
   used). ERA5 Antarctic land cells therefore cannot enter sector means.
3. Removes each sector's calendar-month climatology before correlations.
4. Computes r(lag) = corr[SIC(t), driver(t + lag)] separately for every sector.
5. Adjusts p-values for serial correlation through an effective sample size
   based on lag-1 autocorrelation of the paired series.
6. Applies Benjamini-Hochberg FDR across all sector x lag tests within each
   driver panel.  Stars mark q_FDR < 0.05, not uncorrected p < 0.05.
7. Makes all titles, variables, ticks, axis labels, annotations, and colourbar
   text bold.
8. Builds surface ocean-current speed at every grid cell as sqrt(uo**2 +
   vo**2), after combining the two eastward and two northward time segments.

OHC source priority
-------------------
1. Existing sea-wise Argo OHC CSV generated by the Fig. 5 code.
2. Existing gridded Argo OHC NetCDF cache generated by the Fig. 4 code.
3. Raw Argo profile file.  This last fallback is slow and is cached to CSV.

Google Colab installation cell, if required:
    %pip install -q h5netcdf netCDF4 xarray "dask[array]" scipy matplotlib gsw
"""

from pathlib import Path
import gc
import warnings

import matplotlib.pyplot as plt
from matplotlib.colors import TwoSlopeNorm
from matplotlib.gridspec import GridSpec
import numpy as np
import pandas as pd
from scipy.stats import pearsonr, t as student_t
import xarray as xr

warnings.filterwarnings("ignore")



# 1. PATHS

DATA_DIR = Path("/content/drive/MyDrive/SAM_Thesis/Data")
FIG_DIR = Path("/content/drive/MyDrive/SAM_Thesis/Fig")
SUPP_DIR = FIG_DIR / "Fig10_lag_correlation_supplementary"

SST_FILE = DATA_DIR / "OSTIA_SST_monthly_2008_2025_SO.nc"
SIC_FILE = DATA_DIR / "OSTIA_sea_ice_fraction_monthly_2008_2025_SO.nc"
WIND_FILE = DATA_DIR / "Wind_U_V_era.nc"
T2M_FILE = DATA_DIR / "2mT_MSLP_era.nc"
MLD_FILE = DATA_DIR / "MLD_monthly_2008_2025_SO.nc"

EASTWARD_CURRENT_FILES = [
    DATA_DIR / "EastwardSeaWaterVelocity_uo_2008_14 .nc",
    DATA_DIR / "EastwardSeaWaterVelocity_uo_2015_25 .nc",
]

NORTHWARD_CURRENT_FILES = [
    DATA_DIR / "NorthwardSeaWaterVelocity_uo_2008_14 .nc",
    DATA_DIR / "NorthwardSeaWaterVelocity_uo_2015_25 .nc",
]

# Preferred existing sea-wise OHC cache from the Fig. 5 workflow.
OHC_SEAWISE_CSV_CANDIDATES = [
    FIG_DIR / "Fig5_OHC_supplementary" / "Argo_monthly_OHC_0_100m_GJ_m2.csv",
    SUPP_DIR / "Argo_monthly_OHC_0_100m_GJ_m2.csv",
]

# Existing 2-degree gridded cache produced during the corrected Fig. 4 run.
OHC_GRIDDED_CACHE_FILE = (
    FIG_DIR
    / "Fig4_spatial_correlation_supplementary"
    / "Argo_monthly_gridded_OHC_0_100m_2deg.nc"
)

# Used only when neither OHC cache exists.
ARGO_PROFILE_FILE = DATA_DIR / "argo_SO_profiles_2001_2025_cleaned_gridded.nc"

OUT_PNG = FIG_DIR / "Fig10_sectorwise_lag_correlations_corrected.png"
OUT_PDF = FIG_DIR / "Fig10_sectorwise_lag_correlations_corrected.pdf"
OUT_RESULTS_CSV = SUPP_DIR / "Fig10_sector_lag_statistics.csv"
OUT_FDR_SUMMARY_CSV = SUPP_DIR / "Fig10_panel_FDR_summary.csv"
OUT_ZERO_LAG_CSV = SUPP_DIR / "Fig10_zero_lag_summary.csv"
OUT_PEAK_LAG_CSV = SUPP_DIR / "Fig10_peak_absolute_lag_by_sector_driver.csv"
OUT_SIGNIFICANT_CSV = SUPP_DIR / "Fig10_FDR_significant_lag_results.csv"
OUT_CURRENT_MONTHLY_CSV = (
    SUPP_DIR / "Ocean_Current_Speed_seawise_monthly_2008_2025.csv"
)
OUT_CURRENT_ANOMALY_CSV = (
    SUPP_DIR / "Ocean_Current_Speed_seawise_monthly_anomalies_2008_2025.csv"
)
OUT_CURRENT_COVERAGE_CSV = SUPP_DIR / "Ocean_Current_Speed_monthly_coverage.csv"
OUT_CURRENT_SOURCE_CSV = SUPP_DIR / "Ocean_Current_input_files_and_variables.csv"
OUT_METHODS_TXT = SUPP_DIR / "Fig10_methods_verification.txt"



# 2. ANALYSIS SETTINGS

START_YEAR = 2008
END_YEAR = 2025
TARGET_RES_DEG = 0.25
LAGS = np.arange(-6, 7, dtype=int)

MIN_VALID_PAIRS = 12
MIN_CLIM_OBS_PER_CALENDAR_MONTH = 3
FDR_ALPHA = 0.05

FIGURE_SIZE_INCHES = (15.5, 14.2)
SAVE_DPI = 1080



# 3. THE SAME 13 ANTARCTIC MARGINAL-SEA SECTORS


SEA_INFO = [
    ("WED", "Weddell Sea",            -60,  -20),
    ("KHV", "King Haakon VII Sea",    -20,    0),
    ("RLS", "Riiser-Larsen Sea",        0,   10),
    ("LAZ", "Lazarev Sea",             10,   30),
    ("COS", "Cosmonauts Sea",          30,   50),
    ("COO", "Cooperation Sea",         50,   70),
    ("DAV", "Davis Sea",               70,   90),
    ("MAW", "Mawson Sea",              90,  130),
    ("DUR", "D'Urville Sea",          130,  150),
    ("SOM", "Somov Sea",              150,  170),
    ("ROS", "Ross Sea",               170, -130),  # crosses date line
    ("AMU", "Amundsen Sea",          -130, -100),
    ("BEL", "Bellingshausen Sea",    -100,  -60),
]

SEA_CODES = [item[0] for item in SEA_INFO]
SEA_NAMES = {item[0]: item[1] for item in SEA_INFO}



# 4. ARGO OHC SETTINGS — USED ONLY BY THE RAW-PROFILE FALLBACK


OHC_GRID_DBAR = np.arange(0.0, 101.0, 1.0)
MAX_SHALLOWEST_VALID_DBAR = 10.0
MIN_DEEPEST_VALID_DBAR = 90.0
MIN_VALID_LEVELS_OHC = 8
MIN_ARGO_PROFILES_PER_MONTH = 1
CP0 = 3991.86795711963  # J kg-1 K-1, TEOS-10 reference heat capacity



# 5. DATASET AND MASK HELPERS


def open_dataset_robust(path, chunks=None):
    if not Path(path).exists():
        raise FileNotFoundError(f"Input file not found: {path}")

    try:
        return xr.open_dataset(
            path,
            decode_times=True,
            decode_timedelta=False,
            chunks=chunks or {},
        )
    except ImportError as error:
        message = str(error).lower()
        if "dask" not in message and "chunk manager" not in message:
            raise
        print(f"WARNING: Dask unavailable; opening {Path(path).name} without chunks.")
        return xr.open_dataset(
            path,
            decode_times=True,
            decode_timedelta=False,
            chunks=None,
        )


def standardize_dataset(dataset):
    rename = {}
    aliases = {
        "valid_time": "time",
        "time_counter": "time",
        "month": "time",
        "latitude": "lat",
        "nav_lat": "lat",
        "longitude": "lon",
        "nav_lon": "lon",
    }

    available = set(dataset.coords) | set(dataset.dims)
    for old_name, new_name in aliases.items():
        if old_name in available and new_name not in available:
            rename[old_name] = new_name

    if rename:
        dataset = dataset.rename(rename)

    required = {"time", "lat", "lon"}
    missing = required.difference(dataset.coords)
    if missing:
        raise ValueError(f"Missing required coordinates: {sorted(missing)}")

    if dataset["lat"].ndim != 1 or dataset["lon"].ndim != 1:
        raise ValueError("This code requires one-dimensional lat/lon coordinates.")

    dataset = dataset.drop_vars(["number", "expver"], errors="ignore")

    if float(dataset["lon"].max()) > 180.0:
        dataset = dataset.assign_coords(
            lon=((dataset["lon"] + 180.0) % 360.0) - 180.0
        )

    dataset = dataset.sortby("lon").sortby("lat").sortby("time")
    dataset = dataset.sel(
        time=slice(f"{START_YEAR}-01-01", f"{END_YEAR}-12-31")
    )
    return dataset.where(dataset["lat"] <= -60.0, drop=True)


def find_variable(dataset, candidates, descriptive_name):
    for candidate in candidates:
        if candidate in dataset.data_vars:
            return candidate

    lower_lookup = {name.lower(): name for name in dataset.data_vars}
    for candidate in candidates:
        if candidate.lower() in lower_lookup:
            return lower_lookup[candidate.lower()]

    raise ValueError(
        f"Could not find {descriptive_name}. Tried {candidates}. "
        f"Available variables: {list(dataset.data_vars)}"
    )


def resolve_current_input_path(path):
    """Accept current filenames with/without a space and uo/vo north suffix."""
    path = Path(path)
    path_string = str(path)
    candidates = [
        path,
        Path(path_string.replace(" .nc", ".nc")),
        Path(
            path_string.replace(
                "NorthwardSeaWaterVelocity_uo_",
                "NorthwardSeaWaterVelocity_vo_",
            )
        ),
        Path(
            path_string.replace(
                "NorthwardSeaWaterVelocity_uo_",
                "NorthwardSeaWaterVelocity_vo_",
            ).replace(" .nc", ".nc")
        ),
    ]

    for candidate in candidates:
        if candidate.exists():
            return candidate

    return path


def select_surface_current_layer(data_array, component_name):
    """Select the shallowest available depth level for a current component."""
    recognised_depth_names = {
        "depth",
        "depthu",
        "depthv",
        "lev",
        "level",
        "z",
    }
    depth_dimensions = [
        dimension
        for dimension in data_array.dims
        if str(dimension).lower() in recognised_depth_names
    ]

    if not depth_dimensions:
        print(f"{component_name}: no depth dimension; using supplied field.")
        return data_array

    depth_dimension = depth_dimensions[0]
    depth_values = np.asarray(data_array[depth_dimension].values, dtype=float)

    if depth_values.size == 0 or not np.isfinite(depth_values).any():
        raise ValueError(
            f"{component_name}: unusable depth coordinate {depth_dimension}."
        )

    surface_index = int(np.nanargmin(np.abs(depth_values)))
    surface_depth = float(depth_values[surface_index])
    print(
        f"{component_name}: selected shallowest "
        f"{depth_dimension}={surface_depth:g}."
    )
    return data_array.isel({depth_dimension: surface_index}, drop=True)


def load_current_component(file_paths, candidates, component_name):
    """Load, harmonise and concatenate both time segments of uo or vo."""
    pieces = []
    opened_datasets = []
    variable_names = []

    for file_path in file_paths:
        print(f"Opening {component_name}: {file_path}")
        dataset = standardize_dataset(
            open_dataset_robust(file_path, chunks={"time": 12})
        )
        variable_name = find_variable(dataset, candidates, component_name)
        component = dataset[variable_name].astype("float32")
        component = select_surface_current_layer(component, component_name)

        for dimension in list(component.dims):
            if dimension not in {"time", "lat", "lon"}:
                if component.sizes[dimension] == 1:
                    component = component.isel({dimension: 0}, drop=True)
                else:
                    raise ValueError(
                        f"{component_name}: unsupported dimension {dimension} "
                        f"with size {component.sizes[dimension]}."
                    )

        monthly_time = month_start_index(component["time"].values)
        component = component.assign_coords(time=monthly_time)
        if monthly_time.duplicated().any():
            component = component.groupby("time").mean(skipna=True)

        if pieces:
            same_lat = np.array_equal(
                component["lat"].values, pieces[0]["lat"].values
            )
            same_lon = np.array_equal(
                component["lon"].values, pieces[0]["lon"].values
            )
            if not (same_lat and same_lon):
                print(
                    f"{component_name}: aligning {Path(file_path).name} "
                    "to the first segment's grid."
                )
                component = component.interp(
                    lat=pieces[0]["lat"],
                    lon=pieces[0]["lon"],
                    method="linear",
                )

        pieces.append(component)
        opened_datasets.append(dataset)
        variable_names.append(variable_name)

    combined = xr.concat(
        pieces,
        dim="time",
        join="outer",
        combine_attrs="override",
    ).sortby("time")

    combined_time = month_start_index(combined["time"].values)
    combined = combined.assign_coords(time=combined_time)
    if combined_time.duplicated().any():
        combined = combined.groupby("time").mean(skipna=True)

    combined = combined.sel(
        time=slice(f"{START_YEAR}-01-01", f"{END_YEAR}-12-31")
    )
    combined.name = component_name

    print(
        f"{component_name}: variables={variable_names}, "
        f"months={combined.sizes.get('time', 0)}"
    )
    return combined, opened_datasets, variable_names


def coarsen_to_target_resolution(data_array, target_resolution=0.25):
    lon = np.asarray(data_array["lon"].values, dtype=float)
    lat = np.asarray(data_array["lat"].values, dtype=float)

    lon_resolution = float(np.nanmedian(np.abs(np.diff(lon))))
    lat_resolution = float(np.nanmedian(np.abs(np.diff(lat))))

    lon_factor = max(1, int(round(target_resolution / lon_resolution)))
    lat_factor = max(1, int(round(target_resolution / lat_resolution)))

    print(
        f"{data_array.name}: original={data_array.sizes['lat']}x"
        f"{data_array.sizes['lon']}, resolution≈({lat_resolution:.4f}, "
        f"{lon_resolution:.4f})°, coarsen=({lat_factor}, {lon_factor})"
    )

    if lat_factor > 1 or lon_factor > 1:
        data_array = data_array.coarsen(
            lat=lat_factor,
            lon=lon_factor,
            boundary="trim",
        ).mean(skipna=True)

    return data_array


def convert_sic_to_percent(data_array):
    sample = float(
        data_array.isel(time=slice(0, min(12, data_array.sizes["time"])))
        .max(skipna=True)
        .compute()
    )
    if sample <= 1.5:
        data_array = data_array * 100.0

    data_array = data_array.clip(min=0.0, max=100.0).astype("float32")
    data_array.name = "SIC"
    data_array.attrs["units"] = "%"
    return data_array


def convert_kelvin_to_celsius_if_needed(data_array, variable_name):
    units = str(data_array.attrs.get("units", "")).lower()
    sample = float(data_array.isel(time=0).mean(skipna=True).compute())

    if units in {"k", "kelvin"} or sample > 100.0:
        data_array = data_array - 273.15
        print(f"{variable_name}: converted from Kelvin to degrees Celsius.")

    data_array = data_array.astype("float32")
    data_array.name = variable_name
    return data_array


def apply_common_ocean_mask(data_array, ocean_mask):
    """
    Apply the same static SST-derived ocean mask to any lat/lon grid.

    Nearest-neighbour interpolation preserves the categorical mask and removes
    ERA5 land cells before wind/T2m sector averages are calculated.
    """
    mask = ocean_mask.astype("float32")
    same_lat = np.array_equal(mask["lat"].values, data_array["lat"].values)
    same_lon = np.array_equal(mask["lon"].values, data_array["lon"].values)

    if not (same_lat and same_lon):
        mask = mask.interp(
            lat=data_array["lat"],
            lon=data_array["lon"],
            method="nearest",
        )

    return data_array.where(mask > 0.5)


def select_longitude_sector(data_array, lon_min, lon_max):
    longitude = data_array["lon"]
    if lon_min < lon_max:
        condition = (longitude >= lon_min) & (longitude < lon_max)
    else:
        condition = (longitude >= lon_min) | (longitude < lon_max)
    return data_array.where(condition, drop=True)


def area_weighted_mean(data_array):
    weights = np.cos(np.deg2rad(data_array["lat"]))
    weights = weights.where(np.isfinite(weights), 0.0)
    return data_array.weighted(weights).mean(dim=("lat", "lon"), skipna=True)


def month_start_index(time_values):
    return pd.DatetimeIndex(pd.to_datetime(time_values)).to_period("M").to_timestamp()


def sector_monthly_means(data_array, variable_name):
    print(f"\nCalculating common-mask sector means: {variable_name}")
    series_by_sector = {}

    for code, full_name, lon_min, lon_max in SEA_INFO:
        subset = select_longitude_sector(data_array, lon_min, lon_max)
        if subset.sizes.get("lon", 0) == 0 or subset.sizes.get("lat", 0) == 0:
            print(f"  WARNING: {code} has an empty grid selection.")
            series_by_sector[code] = pd.Series(dtype=float)
            continue

        monthly_mean = area_weighted_mean(subset).astype("float32").compute()
        index = month_start_index(monthly_mean["time"].values)
        series = pd.Series(monthly_mean.values, index=index, name=code)
        series = series.groupby(level=0).mean().sort_index()
        series_by_sector[code] = series
        print(f"  {code}: valid months={int(series.notna().sum())}")
        gc.collect()

    full_index = pd.date_range(
        f"{START_YEAR}-01-01", f"{END_YEAR}-12-01", freq="MS"
    )
    result = pd.DataFrame(series_by_sector).reindex(
        index=full_index, columns=SEA_CODES
    )
    result.index.name = "time"
    return result.replace([np.inf, -np.inf], np.nan)


def monthly_anomaly_dataframe(dataframe, minimum_climatology_observations=3):
    """Remove each sector's calendar-month climatology without gap filling."""
    output = pd.DataFrame(index=dataframe.index, columns=dataframe.columns, dtype=float)

    for column in dataframe.columns:
        series = dataframe[column].astype(float)
        anomaly = pd.Series(np.nan, index=series.index, dtype=float)

        for calendar_month in range(1, 13):
            month_mask = series.index.month == calendar_month
            values = series.loc[month_mask]
            valid = values.dropna()
            if len(valid) >= minimum_climatology_observations:
                anomaly.loc[month_mask] = values - valid.mean()

        output[column] = anomaly

    return output



# 6. OHC CACHE AND RAW-ARGO FALLBACK

def normalise_longitude(longitude):
    return ((longitude + 180.0) % 360.0) - 180.0


def sector_code_from_longitude(longitude):
    longitude = float(normalise_longitude(longitude))
    for code, _, lon_min, lon_max in SEA_INFO:
        if lon_min < lon_max:
            if lon_min <= longitude < lon_max:
                return code
        elif longitude >= lon_min or longitude < lon_max:
            return code
    return None


def read_seawise_ohc_csv(path):
    dataframe = pd.read_csv(path)
    lower_columns = {column.lower(): column for column in dataframe.columns}

    # Support the long format: month, sea, OHC_0_100m.
    if {"month", "sea"}.issubset(lower_columns):
        month_column = lower_columns["month"]
        sea_column = lower_columns["sea"]
        value_candidates = [
            column
            for column in dataframe.columns
            if "ohc" in column.lower() and "count" not in column.lower()
        ]
        if not value_candidates:
            raise ValueError(f"No OHC value column found in {path}")
        dataframe[month_column] = pd.to_datetime(dataframe[month_column])
        dataframe = dataframe.pivot_table(
            index=month_column,
            columns=sea_column,
            values=value_candidates[0],
            aggfunc="mean",
        )
    else:
        # Support the wide Fig. 5 cache with the first column named time/month.
        time_candidates = [
            column
            for column in dataframe.columns
            if column.lower() in {"time", "month", "date", "unnamed: 0"}
        ]
        time_column = time_candidates[0] if time_candidates else dataframe.columns[0]
        dataframe[time_column] = pd.to_datetime(dataframe[time_column])
        dataframe = dataframe.set_index(time_column)

    dataframe.index = month_start_index(dataframe.index)
    dataframe.columns = [str(column).upper() for column in dataframe.columns]

    for code in SEA_CODES:
        if code not in dataframe.columns:
            dataframe[code] = np.nan

    full_index = pd.date_range(
        f"{START_YEAR}-01-01", f"{END_YEAR}-12-01", freq="MS"
    )
    dataframe = dataframe.reindex(index=full_index, columns=SEA_CODES)
    dataframe.index.name = "time"
    return dataframe.apply(pd.to_numeric, errors="coerce")


def filled_float_array(values):
    return np.asarray(np.ma.filled(values, np.nan), dtype=np.float64)


def calculate_profile_ohc(p_raw, t_raw, sp_raw, latitude, longitude, gsw_module):
    valid = (
        np.isfinite(p_raw)
        & np.isfinite(t_raw)
        & np.isfinite(sp_raw)
        & (p_raw >= 0.0)
        & (p_raw <= 130.0)
        & (t_raw > -3.0)
        & (t_raw < 20.0)
        & (sp_raw > 20.0)
        & (sp_raw < 42.0)
    )
    if valid.sum() < MIN_VALID_LEVELS_OHC:
        return np.nan

    pressure = np.asarray(p_raw[valid], dtype=float)
    temperature = np.asarray(t_raw[valid], dtype=float)
    salinity = np.asarray(sp_raw[valid], dtype=float)

    order = np.argsort(pressure)
    pressure = pressure[order]
    temperature = temperature[order]
    salinity = salinity[order]

    pressure, unique_indices = np.unique(pressure, return_index=True)
    temperature = temperature[unique_indices]
    salinity = salinity[unique_indices]

    if len(pressure) < MIN_VALID_LEVELS_OHC:
        return np.nan
    if pressure.min() > MAX_SHALLOWEST_VALID_DBAR:
        return np.nan
    if pressure.max() < MIN_DEEPEST_VALID_DBAR:
        return np.nan

    temperature_grid = np.interp(OHC_GRID_DBAR, pressure, temperature)
    salinity_grid = np.interp(OHC_GRID_DBAR, pressure, salinity)

    try:
        absolute_salinity = gsw_module.SA_from_SP(
            salinity_grid, OHC_GRID_DBAR, longitude, latitude
        )
        conservative_temperature = gsw_module.CT_from_t(
            absolute_salinity, temperature_grid, OHC_GRID_DBAR
        )
        freezing_temperature = gsw_module.CT_freezing(
            absolute_salinity, OHC_GRID_DBAR, 0.0
        )
        density = gsw_module.rho(
            absolute_salinity, conservative_temperature, OHC_GRID_DBAR
        )
        depth = -gsw_module.z_from_p(OHC_GRID_DBAR, latitude)
    except Exception:
        return np.nan

    temperature_excess = np.maximum(
        conservative_temperature - freezing_temperature, 0.0
    )
    heat_density = density * CP0 * temperature_excess

    if hasattr(np, "trapezoid"):
        ohc_j_m2 = np.trapezoid(heat_density, depth)
    else:
        ohc_j_m2 = np.trapz(heat_density, depth)

    if not np.isfinite(ohc_j_m2) or ohc_j_m2 < 0.0:
        return np.nan
    return ohc_j_m2 / 1.0e9  # GJ m-2


def build_seawise_ohc_from_raw_argo():
    """Slow fallback used only when neither existing OHC cache is available."""
    if not ARGO_PROFILE_FILE.exists():
        raise FileNotFoundError(
            "No sea-wise OHC CSV, no gridded OHC cache, and no raw Argo file "
            f"were found. Last path checked: {ARGO_PROFILE_FILE}"
        )

    try:
        import gsw
        from netCDF4 import Dataset
    except ImportError as error:
        raise ImportError(
            "Raw Argo OHC construction requires gsw and netCDF4. In Colab run: "
            "%pip install -q gsw netCDF4"
        ) from error

    print("\nNo OHC cache found; building sea-wise OHC from raw Argo profiles.")
    print("This fallback is slow. Its result will be cached for later runs.")
    records = []

    with Dataset(ARGO_PROFILE_FILE, mode="r") as dataset:
        required = ["PRES_GRID", "LATITUDE", "LONGITUDE", "JULD", "TEMP", "PSAL"]
        missing = [name for name in required if name not in dataset.variables]
        if missing:
            raise ValueError(f"Missing Argo variables: {missing}")

        latitudes = filled_float_array(dataset.variables["LATITUDE"][:])
        longitudes = normalise_longitude(
            filled_float_array(dataset.variables["LONGITUDE"][:])
        )
        julian_days = filled_float_array(dataset.variables["JULD"][:])
        times = pd.to_datetime(
            julian_days, unit="D", origin="1950-01-01", errors="coerce"
        )

        pressure_variable = dataset.variables["PRES_GRID"]
        shared_pressure = (
            filled_float_array(pressure_variable[:])
            if pressure_variable.ndim == 1
            else None
        )
        temperature_variable = dataset.variables["TEMP"]
        salinity_variable = dataset.variables["PSAL"]

        candidate = (
            np.isfinite(latitudes)
            & np.isfinite(longitudes)
            & (latitudes >= -90.0)
            & (latitudes <= -60.0)
            & (~pd.isna(times))
            & (times.year >= START_YEAR)
            & (times.year <= END_YEAR)
        )
        indices = np.where(candidate)[0]
        print(f"Candidate Argo profiles: {len(indices):,}")

        for count, profile_index in enumerate(indices, start=1):
            sector = sector_code_from_longitude(longitudes[profile_index])
            if sector is None:
                continue

            pressure = (
                shared_pressure
                if shared_pressure is not None
                else filled_float_array(pressure_variable[profile_index, :])
            )
            temperature = filled_float_array(
                temperature_variable[profile_index, :]
            )
            salinity = filled_float_array(salinity_variable[profile_index, :])

            ohc = calculate_profile_ohc(
                pressure,
                temperature,
                salinity,
                float(latitudes[profile_index]),
                float(longitudes[profile_index]),
                gsw,
            )
            if np.isfinite(ohc):
                records.append(
                    {
                        "time": pd.Timestamp(times[profile_index]).to_period("M").to_timestamp(),
                        "sea": sector,
                        "OHC_0_100m": float(ohc),
                    }
                )

            if count % 5000 == 0:
                print(
                    f"  processed {count:,}/{len(indices):,}; "
                    f"valid OHC profiles={len(records):,}"
                )

    if not records:
        raise RuntimeError("No valid 0–100 m OHC profiles were produced.")

    profiles = pd.DataFrame(records)
    grouped = (
        profiles.groupby(["time", "sea"])["OHC_0_100m"]
        .agg(["mean", "size"])
        .reset_index()
    )
    values = grouped.pivot(index="time", columns="sea", values="mean")
    counts = grouped.pivot(index="time", columns="sea", values="size")

    full_index = pd.date_range(
        f"{START_YEAR}-01-01", f"{END_YEAR}-12-01", freq="MS"
    )
    values = values.reindex(index=full_index, columns=SEA_CODES)
    counts = counts.reindex(index=full_index, columns=SEA_CODES).fillna(0.0)
    values = values.where(counts >= MIN_ARGO_PROFILES_PER_MONTH)
    values.index.name = "time"

    cache_path = SUPP_DIR / "Argo_monthly_OHC_0_100m_GJ_m2.csv"
    values.to_csv(cache_path)
    counts.to_csv(SUPP_DIR / "Argo_monthly_OHC_profile_counts.csv")
    print(f"Saved sea-wise OHC cache: {cache_path}")
    return values


def load_sector_ohc(ocean_mask):
    for csv_path in OHC_SEAWISE_CSV_CANDIDATES:
        if csv_path.exists():
            print(f"\nUsing existing sea-wise OHC cache: {csv_path}")
            return read_seawise_ohc_csv(csv_path), f"sea-wise CSV: {csv_path}"

    if OHC_GRIDDED_CACHE_FILE.exists():
        print(f"\nUsing existing gridded OHC cache: {OHC_GRIDDED_CACHE_FILE}")
        dataset = standardize_dataset(
            open_dataset_robust(OHC_GRIDDED_CACHE_FILE, chunks={"time": 12})
        )
        try:
            variable_name = find_variable(
                dataset,
                [
                    "OHC_0_100m",
                    "ohc_0_100m",
                    "OHC",
                    "ohc",
                    "ocean_heat_content",
                ],
                "OHC 0–100 m",
            )
            ohc = dataset[variable_name].astype("float32")
            ohc.name = "OHC (0–100 m)"
            ohc = apply_common_ocean_mask(ohc, ocean_mask)
            dataframe = sector_monthly_means(ohc, "OHC (0–100 m)")
            dataframe.to_csv(SUPP_DIR / "Argo_monthly_OHC_0_100m_GJ_m2.csv")
        finally:
            dataset.close()
        return dataframe, f"gridded NetCDF cache: {OHC_GRIDDED_CACHE_FILE}"

    dataframe = build_seawise_ohc_from_raw_argo()
    return dataframe, f"raw Argo profiles: {ARGO_PROFILE_FILE}"



# 7. AUTOCORRELATION-AWARE LAG TESTS AND FDR

def lag_one_autocorrelation(values, dates):
    """Lag-1 correlation using only observations exactly one month apart."""
    values = np.asarray(values, dtype=float)
    dates = pd.DatetimeIndex(dates)

    if len(values) < 4:
        return 0.0, 0

    month_number = dates.year * 12 + dates.month
    adjacent = np.diff(month_number) == 1
    first = values[:-1][adjacent]
    second = values[1:][adjacent]
    valid = np.isfinite(first) & np.isfinite(second)
    first = first[valid]
    second = second[valid]

    if len(first) < 4 or np.nanstd(first) == 0.0 or np.nanstd(second) == 0.0:
        return 0.0, int(len(first))

    correlation = float(np.corrcoef(first, second)[0, 1])
    if not np.isfinite(correlation):
        correlation = 0.0
    return float(np.clip(correlation, -0.99, 0.99)), int(len(first))


def effective_sample_size(number, rho_sic, rho_driver):
    """Bretherton-style effective N using the product of lag-1 correlations."""
    product = float(np.clip(rho_sic * rho_driver, -0.99, 0.99))
    estimate = number * (1.0 - product) / (1.0 + product)
    return float(np.clip(estimate, 3.0, float(number)))


def autocorrelation_adjusted_p_value(correlation, effective_n):
    if not np.isfinite(correlation) or effective_n <= 2.0:
        return np.nan

    clipped_r = float(np.clip(correlation, -0.999999, 0.999999))
    statistic = clipped_r * np.sqrt(
        (effective_n - 2.0) / max(1.0e-12, 1.0 - clipped_r**2)
    )
    return float(2.0 * student_t.sf(abs(statistic), df=effective_n - 2.0))


def calculate_one_lag(sic_series, driver_series, lag):
    """Calculate corr[SIC(t), driver(t + lag)] for one sector and lag."""
    shifted_driver = driver_series.copy()
    shifted_driver.index = shifted_driver.index - pd.DateOffset(months=int(lag))

    paired = pd.concat(
        [sic_series.rename("SIC"), shifted_driver.rename("driver")], axis=1
    ).dropna()
    paired = paired.sort_index()
    number = len(paired)

    if number < MIN_VALID_PAIRS:
        return {
            "r": np.nan,
            "p_autocorr": np.nan,
            "n": number,
            "n_eff": np.nan,
            "rho1_sic": np.nan,
            "rho1_driver": np.nan,
            "adjacent_pairs_sic": 0,
            "adjacent_pairs_driver": 0,
        }

    x = paired["SIC"].values.astype(float)
    y = paired["driver"].values.astype(float)
    if np.nanstd(x) == 0.0 or np.nanstd(y) == 0.0:
        return {
            "r": np.nan,
            "p_autocorr": np.nan,
            "n": number,
            "n_eff": np.nan,
            "rho1_sic": np.nan,
            "rho1_driver": np.nan,
            "adjacent_pairs_sic": 0,
            "adjacent_pairs_driver": 0,
        }

    correlation = float(pearsonr(x, y).statistic)
    rho_sic, adjacent_sic = lag_one_autocorrelation(x, paired.index)
    rho_driver, adjacent_driver = lag_one_autocorrelation(y, paired.index)
    n_eff = effective_sample_size(number, rho_sic, rho_driver)
    p_value = autocorrelation_adjusted_p_value(correlation, n_eff)

    return {
        "r": correlation,
        "p_autocorr": p_value,
        "n": number,
        "n_eff": n_eff,
        "rho1_sic": rho_sic,
        "rho1_driver": rho_driver,
        "adjacent_pairs_sic": adjacent_sic,
        "adjacent_pairs_driver": adjacent_driver,
    }


def benjamini_hochberg(p_values):
    """Return BH-adjusted q-values in the original input shape."""
    p_values = np.asarray(p_values, dtype=float)
    q_values = np.full(p_values.shape, np.nan, dtype=float)
    valid_indices = np.flatnonzero(np.isfinite(p_values))

    if len(valid_indices) == 0:
        return q_values

    valid_p = p_values[valid_indices]
    order = np.argsort(valid_p)
    sorted_p = valid_p[order]
    number_tests = len(sorted_p)

    adjusted_sorted = sorted_p * number_tests / np.arange(1, number_tests + 1)
    adjusted_sorted = np.minimum.accumulate(adjusted_sorted[::-1])[::-1]
    adjusted_sorted = np.clip(adjusted_sorted, 0.0, 1.0)

    adjusted_valid = np.empty(number_tests, dtype=float)
    adjusted_valid[order] = adjusted_sorted
    q_values[valid_indices] = adjusted_valid
    return q_values


def calculate_driver_panel(sic_anomalies, driver_anomalies, driver_label):
    rows = []

    for sector in SEA_CODES:
        for lag in LAGS:
            statistics = calculate_one_lag(
                sic_anomalies[sector], driver_anomalies[sector], int(lag)
            )
            rows.append(
                {
                    "Driver": driver_label,
                    "Sector": sector,
                    "Sector_name": SEA_NAMES[sector],
                    "Lag_months": int(lag),
                    **statistics,
                }
            )

    result = pd.DataFrame(rows)
    result["q_fdr"] = benjamini_hochberg(result["p_autocorr"].values)
    result["significant_fdr"] = result["q_fdr"] < FDR_ALPHA
    return result



# 8. PLOTTING

def result_matrix(result, value_column):
    matrix = (
        result.pivot(index="Sector", columns="Lag_months", values=value_column)
        .reindex(index=SEA_CODES, columns=LAGS)
    )
    return matrix.values


def style_bold_tick_labels(axis):
    for label in axis.get_xticklabels() + axis.get_yticklabels():
        label.set_fontweight("bold")


def plot_heatmap_figure(panel_results):
    plt.rcParams.update(
        {
            "font.family": "DejaVu Sans",
            "font.size": 9,
            "font.weight": "bold",
            "axes.titleweight": "bold",
            "axes.labelweight": "bold",
            "axes.linewidth": 1.0,
            "xtick.major.width": 0.9,
            "ytick.major.width": 0.9,
        }
    )

    figure = plt.figure(figsize=FIGURE_SIZE_INCHES, facecolor="white")
    grid = GridSpec(
        3,
        4,
        figure=figure,
        left=0.090,
        right=0.890,
        bottom=0.080,
        top=0.950,
        wspace=0.70,
        hspace=0.45,
    )

    panel_positions = [
        grid[0, 0:2],
        grid[0, 2:4],
        grid[1, 0:2],
        grid[1, 2:4],
        grid[2, 0:2],  # OHC: third-row left
        grid[2, 2:4],  # current speed: third-row right
    ]
    panel_titles = [
        "SIC vs SST",
        "SIC vs Wind Speed",
        "SIC vs MLD",
        "SIC vs Air Temperature",
        "SIC vs OHC (0–100 m)",
        "SIC vs Ocean Current Speed",
    ]
    panel_letters = ["(a)", "(b)", "(c)", "(d)", "(e)", "(f)"]

    colourmap = "RdBu_r"
    normalisation = TwoSlopeNorm(vmin=-1.0, vcenter=0.0, vmax=1.0)
    correlation_ticks = [-1.0, -0.75, -0.50, -0.25, 0.0, 0.25, 0.50, 0.75, 1.0]

    last_image = None

    for panel_index, (title, position) in enumerate(
        zip(panel_titles, panel_positions)
    ):
        axis = figure.add_subplot(position)
        result = panel_results[title]
        correlations = result_matrix(result, "r")
        significance = result_matrix(result, "significant_fdr").astype(bool)

        image = axis.imshow(
            correlations,
            cmap=colourmap,
            norm=normalisation,
            aspect="auto",
            origin="upper",
        )
        last_image = image

        axis.set_title(title, fontsize=14, fontweight="bold", pad=10)
        axis.text(
            -0.10,
            1.08,
            panel_letters[panel_index],
            transform=axis.transAxes,
            ha="left",
            va="top",
            fontsize=14,
            fontweight="bold",
        )

        axis.set_xticks(np.arange(len(LAGS)))
        axis.set_xticklabels(
            [str(lag) for lag in LAGS], fontsize=8.5, fontweight="bold"
        )
        axis.set_yticks(np.arange(len(SEA_CODES)))
        axis.set_yticklabels(SEA_CODES, fontsize=8.5, fontweight="bold")
        axis.set_xlabel("Lag (months)", fontsize=11, fontweight="bold")
        axis.set_ylabel(
            "Antarctic marginal-sea sector", fontsize=10.5, fontweight="bold"
        )
        axis.tick_params(axis="both", which="major", width=0.9, labelsize=8.5)
        style_bold_tick_labels(axis)

        zero_index = int(np.where(LAGS == 0)[0][0])
        axis.axvline(zero_index, color="black", linewidth=1.0, alpha=0.90)

        axis.set_xticks(np.arange(-0.5, len(LAGS), 1.0), minor=True)
        axis.set_yticks(np.arange(-0.5, len(SEA_CODES), 1.0), minor=True)
        axis.grid(which="minor", color="white", linestyle="-", linewidth=0.8)
        axis.tick_params(which="minor", bottom=False, left=False)

        for sector_index in range(len(SEA_CODES)):
            for lag_index in range(len(LAGS)):
                if significance[sector_index, lag_index]:
                    axis.text(
                        lag_index,
                        sector_index,
                        "*",
                        ha="center",
                        va="center",
                        fontsize=10,
                        color="black",
                        fontweight="bold",
                    )

    colorbar_axis = figure.add_axes([0.920, 0.205, 0.018, 0.630])
    colorbar = figure.colorbar(
        last_image,
        cax=colorbar_axis,
        ticks=correlation_ticks,
        extend="both",
    )
    colorbar.set_label(
        "Pearson correlation coefficient (r)",
        fontsize=11,
        fontweight="bold",
        labelpad=9,
    )
    colorbar.ax.tick_params(labelsize=8.5, width=0.9)
    plt.setp(colorbar.ax.get_yticklabels(), fontweight="bold")

    figure.text(
        0.50,
        0.028,
        "Negative lag: driver leads SIC   |   Positive lag: SIC leads driver   |   "
        "* autocorrelation-adjusted p significant after panel-wise BH-FDR "
        f"(q < {FDR_ALPHA:.2f})",
        ha="center",
        va="center",
        fontsize=9.5,
        fontweight="bold",
        bbox={
            "boxstyle": "round,pad=0.35",
            "facecolor": "white",
            "edgecolor": "0.35",
            "linewidth": 0.8,
        },
    )

    figure.savefig(OUT_PNG, dpi=SAVE_DPI, facecolor="white", edgecolor="none")
    figure.savefig(OUT_PDF, dpi=SAVE_DPI, facecolor="white", edgecolor="none")
    plt.show()
    plt.close(figure)



# 9. MAIN


def main():
    FIG_DIR.mkdir(parents=True, exist_ok=True)
    SUPP_DIR.mkdir(parents=True, exist_ok=True)

    eastward_current_files = [
        resolve_current_input_path(path) for path in EASTWARD_CURRENT_FILES
    ]
    northward_current_files = [
        resolve_current_input_path(path) for path in NORTHWARD_CURRENT_FILES
    ]

    required_gridded_files = [
        SIC_FILE,
        SST_FILE,
        WIND_FILE,
        T2M_FILE,
        MLD_FILE,
        *eastward_current_files,
        *northward_current_files,
    ]
    missing = [str(path) for path in required_gridded_files if not path.exists()]
    if missing:
        raise FileNotFoundError("Missing required inputs:\n" + "\n".join(missing))

    datasets = []
    try:
        ds_sic = standardize_dataset(open_dataset_robust(SIC_FILE, {"time": 12}))
        ds_sst = standardize_dataset(open_dataset_robust(SST_FILE, {"time": 12}))
        ds_wind = standardize_dataset(open_dataset_robust(WIND_FILE, {"time": 12}))
        ds_t2m = standardize_dataset(open_dataset_robust(T2M_FILE, {"time": 12}))
        ds_mld = standardize_dataset(open_dataset_robust(MLD_FILE, {"time": 12}))
        datasets.extend([ds_sic, ds_sst, ds_wind, ds_t2m, ds_mld])

        eastward_current, eastward_datasets, eastward_names = (
            load_current_component(
                eastward_current_files,
                [
                    "uo",
                    "eastward_sea_water_velocity",
                    "eastward_velocity",
                    "u",
                ],
                "Eastward Current",
            )
        )
        northward_current, northward_datasets, northward_names = (
            load_current_component(
                northward_current_files,
                [
                    "vo",
                    "northward_sea_water_velocity",
                    "northward_velocity",
                    "v",
                ],
                "Northward Current",
            )
        )
        datasets.extend(eastward_datasets + northward_datasets)

        # If uo and vo are staggered or otherwise use different coordinate
        # centres, interpolate vo to the uo grid before vector magnitude.
        same_current_lat = np.array_equal(
            eastward_current["lat"].values,
            northward_current["lat"].values,
        )
        same_current_lon = np.array_equal(
            eastward_current["lon"].values,
            northward_current["lon"].values,
        )
        if not (same_current_lat and same_current_lon):
            print(
                "Northward Current: interpolating to the eastward-current "
                "grid before calculating speed."
            )
            northward_current = northward_current.interp(
                lat=eastward_current["lat"],
                lon=eastward_current["lon"],
                method="linear",
            )

        eastward_current, northward_current = xr.align(
            eastward_current,
            northward_current,
            join="inner",
        )
        eastward_units = str(
            eastward_current.attrs.get("units", "not provided")
        )
        northward_units = str(
            northward_current.attrs.get("units", "not provided")
        )
        if (
            eastward_units != "not provided"
            and northward_units != "not provided"
            and eastward_units != northward_units
        ):
            print(
                "WARNING: uo and vo units attributes differ: "
                f"uo={eastward_units!r}, vo={northward_units!r}. "
                "Verify the source files before interpreting current speed."
            )
        current_speed = np.sqrt(
            eastward_current**2 + northward_current**2
        ).astype("float32")
        current_speed.name = "Ocean Current Speed"
        current_speed.attrs["long_name"] = "surface ocean current speed"
        current_speed.attrs["units"] = eastward_current.attrs.get(
            "units",
            northward_current.attrs.get("units", "native current units"),
        )

        sic_name = find_variable(
            ds_sic,
            ["SIF", "SIC", "sic", "sea_ice_fraction", "siconc", "ice_conc"],
            "SIC",
        )
        sst_name = find_variable(
            ds_sst, ["SST", "sst", "analysed_sst", "thetao"], "SST"
        )
        mld_name = find_variable(
            ds_mld, ["MLD", "mld", "mlotst", "mlotst_mean"], "MLD"
        )
        u10_name = find_variable(
            ds_wind, ["u10", "U10", "u", "u10m", "eastward_wind"], "U10"
        )
        v10_name = find_variable(
            ds_wind, ["v10", "V10", "v", "v10m", "northward_wind"], "V10"
        )
        t2m_name = find_variable(
            ds_t2m,
            ["t2m", "T2M", "2m_temperature", "air_temperature", "t"],
            "2 m air temperature",
        )

        print("\nDetected variables:")
        print(f"SIC              : {sic_name}")
        print(f"SST              : {sst_name}")
        print(f"MLD              : {mld_name}")
        print(f"10 m zonal wind  : {u10_name}")
        print(f"10 m merid. wind : {v10_name}")
        print(f"2 m temperature  : {t2m_name}")
        print(f"Eastward current : {eastward_names}")
        print(f"Northward current: {northward_names}")
        print(
            "Current speed     : sqrt(uo^2 + vo^2), calculated at each grid cell"
        )

        sic = convert_sic_to_percent(ds_sic[sic_name].astype("float32"))
        sst = convert_kelvin_to_celsius_if_needed(
            ds_sst[sst_name].astype("float32"), "SST"
        )
        mld = ds_mld[mld_name].astype("float32")
        mld.name = "MLD"

        u10 = ds_wind[u10_name].astype("float32")
        v10 = ds_wind[v10_name].astype("float32")
        wind_speed = np.sqrt(u10**2 + v10**2).astype("float32")
        wind_speed.name = "Wind Speed"

        t2m = convert_kelvin_to_celsius_if_needed(
            ds_t2m[t2m_name].astype("float32"), "Air Temperature"
        )

        # Basic physical cleaning before coarsening and masking.
        sst = sst.where((sst > -5.0) & (sst < 30.0))
        mld = mld.where((mld >= 0.0) & (mld < 2000.0))
        wind_speed = wind_speed.where((wind_speed >= 0.0) & (wind_speed < 100.0))
        t2m = t2m.where((t2m > -100.0) & (t2m < 50.0))
        current_speed = current_speed.where(current_speed >= 0.0)

        sic = coarsen_to_target_resolution(sic, TARGET_RES_DEG)
        sst = coarsen_to_target_resolution(sst, TARGET_RES_DEG)
        mld = coarsen_to_target_resolution(mld, TARGET_RES_DEG)
        wind_speed = coarsen_to_target_resolution(wind_speed, TARGET_RES_DEG)
        t2m = coarsen_to_target_resolution(t2m, TARGET_RES_DEG)
        current_speed = coarsen_to_target_resolution(
            current_speed, TARGET_RES_DEG
        )

        # One common static ocean mask, derived from valid OSTIA SST in any month.
        ocean_mask = np.isfinite(sst).any("time")
        ocean_cell_count = int(ocean_mask.sum().compute())

        sic = apply_common_ocean_mask(sic, ocean_mask)
        sst = apply_common_ocean_mask(sst, ocean_mask)
        mld = apply_common_ocean_mask(mld, ocean_mask)
        wind_speed = apply_common_ocean_mask(wind_speed, ocean_mask)
        t2m = apply_common_ocean_mask(t2m, ocean_mask)
        current_speed = apply_common_ocean_mask(current_speed, ocean_mask)
        print(
            f"\nApplied the same SST-derived ocean mask to all gridded variables "
            f"({ocean_cell_count:,} valid SST-grid cells)."
        )

        sic_dataframe = sector_monthly_means(sic, "SIC")
        sst_dataframe = sector_monthly_means(sst, "SST")
        wind_dataframe = sector_monthly_means(wind_speed, "Wind Speed")
        mld_dataframe = sector_monthly_means(mld, "MLD")
        t2m_dataframe = sector_monthly_means(t2m, "Air Temperature")
        current_dataframe = sector_monthly_means(
            current_speed, "Ocean Current Speed"
        )
        ohc_dataframe, ohc_source = load_sector_ohc(ocean_mask)

        master_index = sic_dataframe.index
        ohc_dataframe = ohc_dataframe.reindex(index=master_index, columns=SEA_CODES)
        current_dataframe = current_dataframe.reindex(
            index=master_index, columns=SEA_CODES
        )

        current_anomaly = monthly_anomaly_dataframe(
            current_dataframe, MIN_CLIM_OBS_PER_CALENDAR_MONTH
        )
        current_dataframe.to_csv(OUT_CURRENT_MONTHLY_CSV)
        current_anomaly.to_csv(OUT_CURRENT_ANOMALY_CSV)

        current_coverage_rows = []
        for code in SEA_CODES:
            valid_months = int(current_dataframe[code].notna().sum())
            current_coverage_rows.append(
                {
                    "Sector": code,
                    "Sector_name": SEA_NAMES[code],
                    "Valid_current_speed_months": valid_months,
                    "Expected_months": len(master_index),
                    "Coverage_percent": (
                        100.0 * valid_months / len(master_index)
                        if len(master_index)
                        else np.nan
                    ),
                }
            )
        pd.DataFrame(current_coverage_rows).to_csv(
            OUT_CURRENT_COVERAGE_CSV, index=False
        )

        current_source_rows = []
        for component, file_paths, names in [
            ("Eastward Current", eastward_current_files, eastward_names),
            ("Northward Current", northward_current_files, northward_names),
        ]:
            for file_path, variable_name in zip(file_paths, names):
                component_units = (
                    eastward_units
                    if component == "Eastward Current"
                    else northward_units
                )
                current_source_rows.append(
                    {
                        "Component": component,
                        "Input_file": str(file_path),
                        "NetCDF_variable": variable_name,
                        "Units_attribute": component_units,
                        "Depth_selection": "shallowest available level",
                        "Speed_definition": "sqrt(uo^2 + vo^2) at each grid cell",
                    }
                )
        pd.DataFrame(current_source_rows).to_csv(
            OUT_CURRENT_SOURCE_CSV, index=False
        )

        sic_anomaly = monthly_anomaly_dataframe(
            sic_dataframe, MIN_CLIM_OBS_PER_CALENDAR_MONTH
        )
        driver_anomalies = {
            "SIC vs SST": monthly_anomaly_dataframe(
                sst_dataframe, MIN_CLIM_OBS_PER_CALENDAR_MONTH
            ),
            "SIC vs Wind Speed": monthly_anomaly_dataframe(
                wind_dataframe, MIN_CLIM_OBS_PER_CALENDAR_MONTH
            ),
            "SIC vs MLD": monthly_anomaly_dataframe(
                mld_dataframe, MIN_CLIM_OBS_PER_CALENDAR_MONTH
            ),
            "SIC vs Air Temperature": monthly_anomaly_dataframe(
                t2m_dataframe, MIN_CLIM_OBS_PER_CALENDAR_MONTH
            ),
            "SIC vs OHC (0–100 m)": monthly_anomaly_dataframe(
                ohc_dataframe, MIN_CLIM_OBS_PER_CALENDAR_MONTH
            ),
            "SIC vs Ocean Current Speed": current_anomaly,
        }

        panel_results = {}
        fdr_summary_rows = []

        for driver_label, anomaly_dataframe in driver_anomalies.items():
            print(f"\nCalculating sector-wise lag tests: {driver_label}")
            result = calculate_driver_panel(
                sic_anomaly, anomaly_dataframe, driver_label
            )
            panel_results[driver_label] = result

            tested = result["p_autocorr"].notna()
            significant = result["significant_fdr"].fillna(False)
            significant_p = result.loc[significant, "p_autocorr"]
            p_cutoff = float(significant_p.max()) if len(significant_p) else np.nan

            fdr_summary_rows.append(
                {
                    "Driver": driver_label,
                    "Sector_lag_tests": int(tested.sum()),
                    "FDR_significant_tests": int(significant.sum()),
                    "FDR_significant_percent": (
                        100.0 * significant.sum() / tested.sum() if tested.sum() else np.nan
                    ),
                    "BH_p_cutoff": p_cutoff,
                    "Median_N": float(result.loc[tested, "n"].median()) if tested.any() else np.nan,
                    "Median_N_eff": (
                        float(result.loc[tested, "n_eff"].median()) if tested.any() else np.nan
                    ),
                }
            )
            print(
                f"  tested={int(tested.sum())}, "
                f"FDR-significant={int(significant.sum())}"
            )

        all_results = pd.concat(panel_results.values(), ignore_index=True)
        all_results.to_csv(OUT_RESULTS_CSV, index=False)
        fdr_summary = pd.DataFrame(fdr_summary_rows)
        fdr_summary.to_csv(OUT_FDR_SUMMARY_CSV, index=False)

        # Table-ready zero-lag results for every driver and marginal sea.
        zero_lag_results = all_results.loc[
            all_results["Lag_months"] == 0
        ].copy()
        zero_lag_results = zero_lag_results.sort_values(
            ["Driver", "Sector"],
            key=lambda values: (
                values.map({code: i for i, code in enumerate(SEA_CODES)})
                if values.name == "Sector"
                else values
            ),
        )
        zero_lag_results.to_csv(OUT_ZERO_LAG_CSV, index=False)

        # One strongest absolute-correlation lag per driver and sea. This is
        # descriptive; its panel-wise FDR q-value is retained in the table.
        finite_results = all_results.loc[
            np.isfinite(all_results["r"])
        ].copy()
        finite_results["absolute_r"] = finite_results["r"].abs()
        peak_indices = (
            finite_results.groupby(["Driver", "Sector"], sort=False)[
                "absolute_r"
            ]
            .idxmax()
            .values
        )
        peak_lag_results = finite_results.loc[peak_indices].copy()
        peak_lag_results = peak_lag_results.rename(
            columns={"Lag_months": "Peak_lag_months"}
        )
        peak_lag_results.to_csv(OUT_PEAK_LAG_CSV, index=False)

        significant_results = all_results.loc[
            all_results["significant_fdr"].fillna(False)
        ].copy()
        significant_results.to_csv(OUT_SIGNIFICANT_CSV, index=False)

        methods_lines = [
            "FIGURE 10 — METHODS VERIFICATION",
            f"Period: {START_YEAR}-{END_YEAR}",
            f"Sectors: {', '.join(SEA_CODES)}",
            f"Lags: {LAGS.min()} to {LAGS.max()} months",
            "Lag definition: corr[SIC(t), driver(t + lag)]",
            "Negative lag: driver leads SIC",
            "Positive lag: SIC leads driver",
            "Anomalies: sector-specific calendar-month climatology removed first",
            "Ocean mask: one static SST-validity mask applied to all gridded variables",
            "Autocorrelation: effective sample size from paired-series lag-1 autocorrelation",
            (
                "Multiple testing: Benjamini-Hochberg FDR across every valid "
                "sector x lag test within each driver panel"
            ),
            f"FDR threshold: q < {FDR_ALPHA}",
            f"Minimum valid pairs: {MIN_VALID_PAIRS}",
            f"OHC source: {ohc_source}",
            "Ocean-current input: two eastward and two northward NetCDF files",
            "Ocean-current depth: shallowest available level in each component file",
            "Ocean-current speed: sqrt(uo^2 + vo^2) calculated per grid cell before sector averaging",
            "Ocean-current components: aligned in time and space before speed calculation",
            "",
            fdr_summary.to_string(index=False),
        ]
        OUT_METHODS_TXT.write_text("\n".join(methods_lines), encoding="utf-8")

        print("\nFDR summary:")
        print(fdr_summary.to_string(index=False))

        plot_heatmap_figure(panel_results)

        print(f"\nSaved figure PNG: {OUT_PNG}")
        print(f"Saved figure PDF: {OUT_PDF}")
        print(f"Saved statistics: {OUT_RESULTS_CSV}")
        print(f"Saved FDR summary: {OUT_FDR_SUMMARY_CSV}")
        print(f"Saved zero-lag table: {OUT_ZERO_LAG_CSV}")
        print(f"Saved peak-lag table: {OUT_PEAK_LAG_CSV}")
        print(f"Saved significant-lag table: {OUT_SIGNIFICANT_CSV}")
        print(f"Saved monthly current speed: {OUT_CURRENT_MONTHLY_CSV}")
        print(f"Saved current-speed anomalies: {OUT_CURRENT_ANOMALY_CSV}")
        print(f"Saved current-speed coverage: {OUT_CURRENT_COVERAGE_CSV}")
        print(f"Saved current-source record: {OUT_CURRENT_SOURCE_CSV}")
        print(f"Saved methods record: {OUT_METHODS_TXT}")

    finally:
        for dataset in datasets:
            dataset.close()
        gc.collect()


if __name__ == "__main__":
    main()
